### ISSUE TITLE
Bump version and new NPM

### ISSUE THREAD

**Issue by RogerHardiman** [Scoup/node-pelcod#2]
Hi there
Would it be possible to release a new NPM package please?
I have updated the ReadMe and these would be good to release.

Also I think we can call this 0.5.0 or even 1.0.0 as I'm happy with the software and have been carrying out lots of tests.

Thanks

**Comment by RogerHardiman** [comment]
Have also added an Extended Command sendSetZoomSpeed which I want to use in the RPOS project   https://github.com/BreeeZe/rpos  so a bump and release would be great.

**Comment by Scoup** [comment]
I agree! We should update the package to version 1.0 since is well tested.
