### ISSUE TITLE
RVision SEE Camera

### ISSUE THREAD

**Issue by aline-fidencio** [Scoup/node-pelcod#3]
Hi all!

I have a question and could not find any email I could write to so I decided to open as an issue.

I want to use an RVision SEE Camera on a Seekur Jr. robot. It is connected to a RS232 port.
If I am not wrong it accepts the Pelcon-d protocol. 

Do you think it is possible to use your node to control this camera over the RS232 connector or do I need to convert it to RS485?

Thanks in advance.

Aline

**Comment by RogerHardiman** [comment]
The spec for the cameras says
RS232 or RS422
Visca, Pelco-D, Pelco-D Enhanced

So it looks like you can connect it to a normal RS232 port and then you can use this Node Project to control the camera.

**Comment by RogerHardiman** [comment]
Let us know if it works.

**Comment by aline-fidencio** [comment]
Hi Roger,

Thanks for the quick reply. Then I will try it out and I do hope it works because it will be of huge use for me. I will for sure keep you updated ! And probably also ask for more support, if that is not a problem. 

Kind regards,

Aline

**Comment by aline-fidencio** [comment]
I am totally new with js so I am having lots of problems to understand how to run the example2 to test and use your node.

I changed its source and set the serial port to the one my camera is connected to.

When I run: node example2/example2.js I get the following error:

![screenshot from 2017-07-04 16 52 50](https://user-images.githubusercontent.com/22963640/27841605-547e1a0e-60d9-11e7-910c-c88468a5e471.png)

Can you give me some help? 

Thanks in advance.

Aline

**Comment by RogerHardiman** [comment]
Did you run 
`npm install
`
after checking out the source from GitHub? This builds all the dependencies.

**Comment by aline-fidencio** [comment]
Yes.. I cloned the rep on a folder , changed to the folder and did npm install.. the node_modules folder was created...

**Comment by Scoup** [comment]
This library does not bother about how you get the data, you could even use a USB camera.
It just needs a stream to be passed, it should be a [buffer](https://nodejs.org/api/buffer.html). You could even use a socket and control the camera remotely.

**Comment by Scoup** [comment]
I believe the problem could be related with permission of the user. You need to check how you could connect your camera with node.js.
